### ISSUE TITLE
requireStack: [ '/workspaces/pali-epub/imaginaryUncacheableRequireResolveScript' ]

### ISSUE THREAD

**Issue by cittadhammo** [buddhiko1/pali-epub#1]
Thanks for the project. I run into the following error:

```
@cittadhammo ➜ /workspaces/pali-epub (master) $ npx ts-node .\index.ts
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './.index.ts'
Require stack:
- /workspaces/pali-epub/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:489:16)
    at getProjectSearchDir (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:459:40)
    at phase3 (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:263:27)
    at bootstrap (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:44:30)
    at main (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/workspaces/pali-epub/node_modules/ts-node/dist/bin.js:519:5)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspaces/pali-epub/imaginaryUncacheableRequireResolveScript' ]
}

```

Any Idea ? Thanks and Metta

**Comment by Nirodhiko** [comment]
@cittadhammo  

Hello~
 
I have update readme.md . you can try it again .
My nodejs version: v.18.12.1 .

**Comment by cittadhammo** [comment]
OK, So all went well. I just had to to run `pnpm setup` and **restart Terminal** to be able to install everything, because `pnpm install -g ts-node` through an error :

```
pnpm install -g ts-node
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

Then I get the same error.

```
@cittadhammo ➜ /workspaces/pali-epub (master ✗) $ pnpm install -g ts-node
Packages: +17
+++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/codespace/.local/share/pnpm/store/v3
  Virtual store is at:             .pnpm

/home/codespace/.local/share/pnpm/global/5:
+ ts-node 10.9.1

 WARN  Issues with peer dependencies found
.
└─┬ ts-node 10.9.1
  ├── ✕ missing peer @types/node@"*"
  └── ✕ missing peer typescript@>=2.7
Peer dependencies that should be installed:
  @types/node@"*"   typescript@>=2.7  

Progress: resolved 17, reused 0, downloaded 17, added 17, done
Done in 1.5s
@cittadhammo ➜ /workspaces/pali-epub (master ✗) $ pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 787ms
@cittadhammo ➜ /workspaces/pali-epub (master ✗) $ ts-node .\index.ts
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './.index.ts'
Require stack:
- /workspaces/pali-epub/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/codespace/.local/share/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspaces/pali-epub/imaginaryUncacheableRequireResolveScript' ]
}
@cittadhammo ➜ /workspaces/pali-epub (master ✗) $ 
```

This was in Codespace node v16.19.0

or locally with Node.js v18.13.0


```
development pali-epub % pnpm install -g ts-node
Packages: +17
+++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/development/Library/pnpm/store/v3
  Virtual store is at:             .pnpm

/Users/development/Library/pnpm/global/5:
+ ts-node 10.9.1

 WARN  Issues with peer dependencies found
.
└─┬ ts-node 10.9.1
  ├── ✕ missing peer @types/node@"*"
  └── ✕ missing peer typescript@>=2.7
Peer dependencies that should be installed:
  @types/node@"*"   typescript@>=2.7  

Progress: resolved 17, reused 0, downloaded 17, added 17, done
Done in 2.3s
development@Amaros-iPad-2 pali-epub % pnpm install
 WARN  Moving @types/clear that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving @types/figlet that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving @types/inquirer that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving @types/sharp that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving @types/xml2js that was installed by a different package manager to "node_modules/.ignored
 WARN  8 other warnings
Packages: +156
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/development/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/@napi-rs/canvas-darwin-x64/0.1.34: 10.8 MB/10.8 MB, done
Progress: resolved 164, reused 17, downloaded 139, added 156, done

dependencies:
+ @lesjoursfr/html-to-epub 2.2.2 (3.1.2 is available)
+ @napi-rs/canvas 0.1.34
+ @types/text-to-svg 3.1.1
+ clear 0.1.0
+ inquirer 8.2.5 (9.1.4 is available)
+ ts-node 10.9.1
+ tsc 2.0.4
+ xml2js 0.4.23

devDependencies:
+ @types/clear 0.1.2
+ @types/figlet 1.5.5
+ @types/inquirer 8.2.5 (9.0.3 is available)
+ @types/sharp 0.30.5 (0.31.1 is available)
+ @types/xml2js 0.4.11

 WARN  Issues with peer dependencies found
.
└─┬ ts-node 10.9.1
  ├── ✕ missing peer @types/node@"*"
  └── ✕ missing peer typescript@>=2.7
Peer dependencies that should be installed:
  @types/node@"*"   typescript@>=2.7  

Done in 23.1s
development pali-epub % ts-node .\index.ts
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module './.index.ts'
Require stack:
- /Users/development/Documents/GitHub/pali-epub/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/development/Library/pnpm/global/5/.pnpm/ts-node@10.9.1/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/development/Documents/GitHub/pali-epub/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v18.13.0
```
